/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Addr = string;
export type ProposalModuleStatus = "Enabled" | "Disabled";
export type ActiveProposalModulesResponse = ProposalModule[];
export interface ProposalModule {
  address: Addr;
  prefix: string;
  status: ProposalModuleStatus;
  [k: string]: unknown;
}
export interface AdminNominationResponse {
  nomination?: Addr | null;
  [k: string]: unknown;
}
export type AdminResponse = Addr | null;
export interface ConfigResponse {
  automatically_add_cw20s: boolean;
  automatically_add_cw721s: boolean;
  banner?: string | null;
  dao_uri?: string | null;
  description: string;
  logo?: string | null;
  name: string;
  [k: string]: unknown;
}
export type Uint128 = string;
export interface Cw20BalancesResponse {
  addr: Addr;
  balance: Uint128;
  [k: string]: unknown;
}
export type Cw20TokenListResponse = Addr[];
export type Cw721TokenListResponse = Addr[];
export type DaoURIResponse = string | null;
export type Timestamp = Uint64;
export type Uint64 = string;
export type PauseInfoResponse = {
  Paused: {
    expiration: Expiration;
    [k: string]: unknown;
  };
} | {
  Unpaused: {
    [k: string]: unknown;
  };
};
export type Expiration = {
  at_height: number;
} | {
  at_time: Timestamp;
} | {
  never: {
    [k: string]: unknown;
  };
};
export interface DumpStateResponse {
  active_proposal_module_count: number;
  admin: Addr;
  config: Config;
  created_timestamp?: Timestamp | null;
  pause_info: PauseInfoResponse;
  proposal_modules: ProposalModule[];
  registered_name?: string | null;
  total_proposal_module_count: number;
  version: ContractVersion;
  voting_module: Addr;
  [k: string]: unknown;
}
export interface Config {
  automatically_add_cw20s: boolean;
  automatically_add_cw721s: boolean;
  banner?: string | null;
  dao_uri?: string | null;
  description: string;
  logo?: string | null;
  name: string;
  [k: string]: unknown;
}
export interface ContractVersion {
  contract: string;
  version: string;
  [k: string]: unknown;
}
export type ExecuteMsg = {
  execute_admin_msgs: {
    msgs: CosmosMsgForEmpty[];
    [k: string]: unknown;
  };
} | {
  execute_proposal_hook: {
    msgs: CosmosMsgForEmpty[];
    [k: string]: unknown;
  };
} | {
  pause: {
    duration: Duration;
    [k: string]: unknown;
  };
} | {
  receive: Cw20ReceiveMsg;
} | {
  receive_nft: Cw721ReceiveMsg;
} | {
  remove_item: {
    key: string;
    [k: string]: unknown;
  };
} | {
  set_item: {
    addr: string;
    key: string;
    [k: string]: unknown;
  };
} | {
  nominate_admin: {
    admin?: string | null;
    [k: string]: unknown;
  };
} | {
  accept_admin_nomination: {
    [k: string]: unknown;
  };
} | {
  withdraw_admin_nomination: {
    [k: string]: unknown;
  };
} | {
  update_config: {
    config: Config;
    [k: string]: unknown;
  };
} | {
  update_cw20_list: {
    to_add: string[];
    to_remove: string[];
    [k: string]: unknown;
  };
} | {
  update_cw721_list: {
    to_add: string[];
    to_remove: string[];
    [k: string]: unknown;
  };
} | {
  update_proposal_modules: {
    to_add: ModuleInstantiateInfo[];
    to_disable: string[];
    [k: string]: unknown;
  };
} | {
  update_voting_module: {
    module: ModuleInstantiateInfo;
    [k: string]: unknown;
  };
} | {
  update_sub_daos: {
    to_add: SubDao[];
    to_remove: string[];
    [k: string]: unknown;
  };
};
export type CosmosMsgForEmpty = {
  bank: BankMsg;
} | {
  custom: Empty;
} | {
  staking: StakingMsg;
} | {
  distribution: DistributionMsg;
} | {
  stargate: {
    type_url: string;
    value: Binary;
    [k: string]: unknown;
  };
} | {
  ibc: IbcMsg;
} | {
  wasm: WasmMsg;
} | {
  gov: GovMsg;
};
export type BankMsg = {
  send: {
    amount: Coin[];
    to_address: string;
    [k: string]: unknown;
  };
} | {
  burn: {
    amount: Coin[];
    [k: string]: unknown;
  };
};
export type StakingMsg = {
  delegate: {
    amount: Coin;
    validator: string;
    [k: string]: unknown;
  };
} | {
  undelegate: {
    amount: Coin;
    validator: string;
    [k: string]: unknown;
  };
} | {
  redelegate: {
    amount: Coin;
    dst_validator: string;
    src_validator: string;
    [k: string]: unknown;
  };
};
export type DistributionMsg = {
  set_withdraw_address: {
    address: string;
    [k: string]: unknown;
  };
} | {
  withdraw_delegator_reward: {
    validator: string;
    [k: string]: unknown;
  };
};
export type Binary = string;
export type IbcMsg = {
  transfer: {
    amount: Coin;
    channel_id: string;
    timeout: IbcTimeout;
    to_address: string;
    [k: string]: unknown;
  };
} | {
  send_packet: {
    channel_id: string;
    data: Binary;
    timeout: IbcTimeout;
    [k: string]: unknown;
  };
} | {
  close_channel: {
    channel_id: string;
    [k: string]: unknown;
  };
};
export type WasmMsg = {
  execute: {
    contract_addr: string;
    funds: Coin[];
    msg: Binary;
    [k: string]: unknown;
  };
} | {
  instantiate: {
    admin?: string | null;
    code_id: number;
    funds: Coin[];
    label: string;
    msg: Binary;
    [k: string]: unknown;
  };
} | {
  migrate: {
    contract_addr: string;
    msg: Binary;
    new_code_id: number;
    [k: string]: unknown;
  };
} | {
  update_admin: {
    admin: string;
    contract_addr: string;
    [k: string]: unknown;
  };
} | {
  clear_admin: {
    contract_addr: string;
    [k: string]: unknown;
  };
};
export type GovMsg = {
  vote: {
    proposal_id: number;
    vote: VoteOption;
    [k: string]: unknown;
  };
};
export type VoteOption = "yes" | "no" | "abstain" | "no_with_veto";
export type Duration = {
  height: number;
} | {
  time: number;
};
export type Admin = {
  address: {
    addr: string;
    [k: string]: unknown;
  };
} | {
  core_contract: {
    [k: string]: unknown;
  };
} | {
  none: {
    [k: string]: unknown;
  };
};
export interface Coin {
  amount: Uint128;
  denom: string;
  [k: string]: unknown;
}
export interface Empty {
  [k: string]: unknown;
}
export interface IbcTimeout {
  block?: IbcTimeoutBlock | null;
  timestamp?: Timestamp | null;
  [k: string]: unknown;
}
export interface IbcTimeoutBlock {
  height: number;
  revision: number;
  [k: string]: unknown;
}
export interface Cw20ReceiveMsg {
  amount: Uint128;
  msg: Binary;
  sender: string;
  [k: string]: unknown;
}
export interface Cw721ReceiveMsg {
  msg: Binary;
  sender: string;
  token_id: string;
  [k: string]: unknown;
}
export interface ModuleInstantiateInfo {
  admin: Admin;
  code_id: number;
  label: string;
  msg: Binary;
  [k: string]: unknown;
}
export interface SubDao {
  addr: string;
  charter?: string | null;
  [k: string]: unknown;
}
export interface GetItemResponse {
  item?: string | null;
  [k: string]: unknown;
}
export interface InfoResponse {
  info: ContractVersion;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  admin?: string | null;
  automatically_add_cw20s: boolean;
  automatically_add_cw721s: boolean;
  banner?: string | null;
  dao_uri?: string | null;
  description: string;
  initial_items?: InitialItem[] | null;
  logo?: string | null;
  name: string;
  name_register_info: NameRegisterInfo;
  proposal_modules_instantiate_info: ModuleInstantiateInfo[];
  voting_module_instantiate_info: ModuleInstantiateInfo;
  [k: string]: unknown;
}
export interface InitialItem {
  key: string;
  value: string;
  [k: string]: unknown;
}
export interface NameRegisterInfo {
  contract_address: Addr;
  msg: Binary;
  [k: string]: unknown;
}
export type ListItemsResponse = string[];
export type ListSubDaosResponse = SubDao[];
export type MigrateMsg = {
  from_v1: {
    dao_uri?: string | null;
    [k: string]: unknown;
  };
} | {
  from_compatible: {
    [k: string]: unknown;
  };
};
export type ProposalModulesResponse = ProposalModule[];
export type QueryMsg = {
  admin: {
    [k: string]: unknown;
  };
} | {
  admin_nomination: {
    [k: string]: unknown;
  };
} | {
  config: {
    [k: string]: unknown;
  };
} | {
  cw20_balances: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  cw20_token_list: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  cw721_token_list: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  dump_state: {
    [k: string]: unknown;
  };
} | {
  get_item: {
    key: string;
    [k: string]: unknown;
  };
} | {
  list_items: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  proposal_modules: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  active_proposal_modules: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  pause_info: {
    [k: string]: unknown;
  };
} | {
  voting_module: {
    [k: string]: unknown;
  };
} | {
  list_sub_daos: {
    limit?: number | null;
    start_after?: string | null;
    [k: string]: unknown;
  };
} | {
  dao_u_r_i: {
    [k: string]: unknown;
  };
} | {
  voting_power_at_height: {
    address: string;
    height?: number | null;
    [k: string]: unknown;
  };
} | {
  total_power_at_height: {
    height?: number | null;
    [k: string]: unknown;
  };
} | {
  info: {
    [k: string]: unknown;
  };
};
export interface TotalPowerAtHeightResponse {
  height: number;
  power: Uint128;
  [k: string]: unknown;
}
export type VotingModuleResponse = string;
export interface VotingPowerAtHeightResponse {
  height: number;
  power: Uint128;
  [k: string]: unknown;
}
export type CWCoreExecuteMsg = ExecuteMsg;