/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "cosmwasm";
import { Binary } from "./CWAdminFactory.types";
export interface CWAdminFactoryMessage {
    contractAddress: string;
    sender: string;
    instantiateContractWithSelfAdmin: ({ codeId, instantiateMsg, label }: {
        codeId: number;
        instantiateMsg: Binary;
        label: string;
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export declare class CWAdminFactoryMessageComposer implements CWAdminFactoryMessage {
    sender: string;
    contractAddress: string;
    constructor(sender: string, contractAddress: string);
    instantiateContractWithSelfAdmin: ({ codeId, instantiateMsg, label }: {
        codeId: number;
        instantiateMsg: Binary;
        label: string;
    }, funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
