/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { Coin, StdFee } from "@cosmjs/amino";
import { SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Binary } from "./CWAdminFactory.types";
export interface CWAdminFactoryInterface {
    contractAddress: string;
    sender: string;
    instantiateContractWithSelfAdmin: ({ codeId, instantiateMsg, label }: {
        codeId: number;
        instantiateMsg: Binary;
        label: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class CWAdminFactoryClient implements CWAdminFactoryInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    instantiateContractWithSelfAdmin: ({ codeId, instantiateMsg, label }: {
        codeId: number;
        instantiateMsg: Binary;
        label: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
