/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Uint128, ClaimsResponse, DaoResponse, Duration, GetConfigResponse, InfoResponse, ListStakersResponse, TotalPowerAtHeightResponse, VotingPowerAtHeightResponse } from "./CWNativeStakedBalanceVoting.types";
export interface CWNativeStakedBalanceVotingReadOnlyInterface {
    contractAddress: string;
    dao: () => Promise<DaoResponse>;
    getConfig: () => Promise<GetConfigResponse>;
    claims: ({ address }: {
        address: string;
    }) => Promise<ClaimsResponse>;
    listStakers: ({ limit, startAfter }: {
        limit?: number;
        startAfter?: string;
    }) => Promise<ListStakersResponse>;
    votingPowerAtHeight: ({ address, height }: {
        address: string;
        height?: number;
    }) => Promise<VotingPowerAtHeightResponse>;
    totalPowerAtHeight: ({ height }: {
        height?: number;
    }) => Promise<TotalPowerAtHeightResponse>;
    info: () => Promise<InfoResponse>;
}
export declare class CWNativeStakedBalanceVotingQueryClient implements CWNativeStakedBalanceVotingReadOnlyInterface {
    client: CosmWasmClient;
    contractAddress: string;
    constructor(client: CosmWasmClient, contractAddress: string);
    dao: () => Promise<DaoResponse>;
    getConfig: () => Promise<GetConfigResponse>;
    claims: ({ address }: {
        address: string;
    }) => Promise<ClaimsResponse>;
    listStakers: ({ limit, startAfter }: {
        limit?: number;
        startAfter?: string;
    }) => Promise<ListStakersResponse>;
    votingPowerAtHeight: ({ address, height }: {
        address: string;
        height?: number;
    }) => Promise<VotingPowerAtHeightResponse>;
    totalPowerAtHeight: ({ height }: {
        height?: number;
    }) => Promise<TotalPowerAtHeightResponse>;
    info: () => Promise<InfoResponse>;
}
export interface CWNativeStakedBalanceVotingInterface extends CWNativeStakedBalanceVotingReadOnlyInterface {
    contractAddress: string;
    sender: string;
    stake: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    unstake: ({ amount }: {
        amount: Uint128;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    updateConfig: ({ duration, manager, owner }: {
        duration?: Duration;
        manager?: string;
        owner?: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    claim: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
export declare class CWNativeStakedBalanceVotingClient extends CWNativeStakedBalanceVotingQueryClient implements CWNativeStakedBalanceVotingInterface {
    client: SigningCosmWasmClient;
    sender: string;
    contractAddress: string;
    constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string);
    stake: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    unstake: ({ amount }: {
        amount: Uint128;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    updateConfig: ({ duration, manager, owner }: {
        duration?: Duration;
        manager?: string;
        owner?: string;
    }, fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
    claim: (fee?: number | StdFee | "auto", memo?: string, funds?: Coin[]) => Promise<ExecuteResult>;
}
