/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/
import * as _1 from "./CWAdminFactory.client";
import * as _2 from "./CWAdminFactory.message-composer";
import * as _4 from "./CWCore.client";
import * as _5 from "./CWCore.message-composer";
import * as _7 from "./CWNamedGroups.client";
import * as _8 from "./CWNamedGroups.message-composer";
import * as _10 from "./CWNamesRegistry.client";
import * as _11 from "./CWNamesRegistry.message-composer";
import * as _13 from "./CWNativeStakedBalanceVoting.client";
import * as _14 from "./CWNativeStakedBalanceVoting.message-composer";
import * as _16 from "./CWProposalMultiple.client";
import * as _17 from "./CWProposalMultiple.message-composer";
import * as _19 from "./CWProposalSingle.client";
import * as _20 from "./CWProposalSingle.message-composer";
import * as _22 from "./CWTokenSwap.client";
import * as _23 from "./CWTokenSwap.message-composer";
import * as _25 from "./CW4Voting.client";
import * as _26 from "./CW4Voting.message-composer";
import * as _28 from "./Profiles.client";
import * as _29 from "./Profiles.message-composer";
export declare namespace contracts {
    const CWAdminFactory: {
        CWAdminFactoryMessageComposer: typeof _2.CWAdminFactoryMessageComposer;
        CWAdminFactoryClient: typeof _1.CWAdminFactoryClient;
    };
    const CWCore: {
        CWCoreMessageComposer: typeof _5.CWCoreMessageComposer;
        CWCoreQueryClient: typeof _4.CWCoreQueryClient;
        CWCoreClient: typeof _4.CWCoreClient;
    };
    const CWNamedGroups: {
        CWNamedGroupsMessageComposer: typeof _8.CWNamedGroupsMessageComposer;
        CWNamedGroupsQueryClient: typeof _7.CWNamedGroupsQueryClient;
        CWNamedGroupsClient: typeof _7.CWNamedGroupsClient;
    };
    const CWNamesRegistry: {
        CWNamesRegistryMessageComposer: typeof _11.CWNamesRegistryMessageComposer;
        CWNamesRegistryQueryClient: typeof _10.CWNamesRegistryQueryClient;
        CWNamesRegistryClient: typeof _10.CWNamesRegistryClient;
    };
    const CWNativeStakedBalanceVoting: {
        CWNativeStakedBalanceVotingMessageComposer: typeof _14.CWNativeStakedBalanceVotingMessageComposer;
        CWNativeStakedBalanceVotingQueryClient: typeof _13.CWNativeStakedBalanceVotingQueryClient;
        CWNativeStakedBalanceVotingClient: typeof _13.CWNativeStakedBalanceVotingClient;
    };
    const CWProposalMultiple: {
        CWProposalMultipleMessageComposer: typeof _17.CWProposalMultipleMessageComposer;
        CWProposalMultipleQueryClient: typeof _16.CWProposalMultipleQueryClient;
        CWProposalMultipleClient: typeof _16.CWProposalMultipleClient;
    };
    const CWProposalSingle: {
        CWProposalSingleMessageComposer: typeof _20.CWProposalSingleMessageComposer;
        CWProposalSingleQueryClient: typeof _19.CWProposalSingleQueryClient;
        CWProposalSingleClient: typeof _19.CWProposalSingleClient;
    };
    const CWTokenSwap: {
        CWTokenSwapMessageComposer: typeof _23.CWTokenSwapMessageComposer;
        CWTokenSwapQueryClient: typeof _22.CWTokenSwapQueryClient;
        CWTokenSwapClient: typeof _22.CWTokenSwapClient;
    };
    const CW4Voting: {
        CW4VotingMessageComposer: typeof _26.CW4VotingMessageComposer;
        CW4VotingQueryClient: typeof _25.CW4VotingQueryClient;
        CW4VotingClient: typeof _25.CW4VotingClient;
    };
    const Profiles: {
        ProfilesMessageComposer: typeof _29.ProfilesMessageComposer;
        ProfilesQueryClient: typeof _28.ProfilesQueryClient;
        ProfilesClient: typeof _28.ProfilesClient;
    };
}
